// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlh54PuoZXPZ7sBgosjWdvxmqiwZgInnQ',
    appId: '1:100870885548:web:51100421df9adc58e7cf09',
    messagingSenderId: '100870885548',
    projectId: 'webtutorial-2f222',
    authDomain: 'webtutorial-2f222.firebaseapp.com',
    storageBucket: 'webtutorial-2f222.firebasestorage.app',
    measurementId: 'G-97V61JJR44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEAC8aVOzYbi7gQMgs4rhIpoiHbHhVLFk',
    appId: '1:100870885548:android:e6ce4a4700ee9d4ce7cf09',
    messagingSenderId: '100870885548',
    projectId: 'webtutorial-2f222',
    storageBucket: 'webtutorial-2f222.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzqb9DlwWtnAnyB0zxF9DYXbql7VxYTDI',
    appId: '1:100870885548:ios:15b99371cb909edde7cf09',
    messagingSenderId: '100870885548',
    projectId: 'webtutorial-2f222',
    storageBucket: 'webtutorial-2f222.firebasestorage.app',
    iosBundleId: 'com.example.phonecall',
  );

}